server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://localhost:1433/demoapp
    username: sa
    password: verYs3cret
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 829190185645-b21m1okcdneph59lrcgv7ldk4546sfcg.apps.googleusercontent.com
            client-secret: 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
springdoc:
  swagger-ui:
    path: /swagger-ui.html

test:
  test1:
    test2: dupa